//level-1
console.log('10'===10)
console.log('10'==10)
console.log(parseInt('10')==10)
console.log("TRUTHY VALUES")
console.log(1==true)
console.log(undefined==null)
console.log(0==" ")
console.log("FALSY VALUES")
console.log(NaN==NaN)
console.log(0===false)
console.log(5==='5')
console.log("python".length<"jargon".length)
console.log(4 > 3)
console.log(4 >= 3)
console.log(4 < 3)
console.log(4 <= 3)
console.log(4 ==4)
console.log(4 === 4)
console.log(4 != 4)
console.log(4 !== 4)
console.log(4 == "4")
console.log(4 === "4")
console.log("dragon".includes("on") && "python".includes("on"))
console.log("DATE")
let now=new Date();
let date=now.getDate();
let month=now.getMonth()+1;
let year=now.getFullYear()
console.log(now)
console.log(date+"-"+month+"-"+year)
console.log("the numbers of seconds elapsed from January 1, 1970 to now: "+now.getTime())
